# Generated by Django 5.2.7 on 2025-10-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
