# Generated by Django 5.2.7 on 2025-11-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0003_alter_courses_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.BooleanField()),
                ('educational_qualification', models.CharField()),
                ('mobile_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_occupation', models.CharField(max_length=100)),
                ('guardian_phone', models.BigIntegerField()),
                ('choose_course', models.CharField(max_length=150)),
                ('training_mode', models.BooleanField()),
                ('location', models.BooleanField()),
                ('timing', models.BooleanField()),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
            ],
        ),
    ]
