# Generated by Django 5.2.7 on 2025-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0004_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(default='mm/dd/yy'),
        ),
    ]
