# Generated by Django 5.2.7 on 2025-11-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0008_alter_registration_address_alter_registration_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='educational_qualification',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
