# Generated by Django 5.2.7 on 2025-11-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0009_alter_registration_educational_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='hobbies',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='photo',
            field=models.FileField(default='NA', upload_to='documents'),
        ),
    ]
