# Generated by Django 5.2.7 on 2025-11-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0012_registration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='confirm_password',
            field=models.CharField(default='NA', max_length=8, null=True),
        ),
    ]
