# Generated by Django 5.2.7 on 2025-11-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0013_registration_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='otp_db',
            field=models.CharField(default='NA', max_length=5, null=True),
        ),
    ]
