# Generated by Django 5.2.8 on 2025-11-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0014_registration_otp_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='remember_me',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
