# Generated by Django 5.2.7 on 2025-11-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0016_alter_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='remember_me',
            field=models.CharField(default='False', max_length=10, null=True),
        ),
    ]
