# Generated by Django 5.2.7 on 2025-12-02 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0018_remove_state_country_alter_registration_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scopeweb.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scopeweb.state')),
            ],
        ),
    ]
