# Generated by Django 5.2.7 on 2025-12-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0019_state_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.AddField(
            model_name='registration',
            name='existing_password',
            field=models.CharField(default='NA', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='photo',
            field=models.FileField(default='media\\documentsĄ2356.png', null=True, upload_to='documents'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
