# Generated by Django 5.2.7 on 2025-12-04 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0020_remove_state_country_registration_existing_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.CharField(db_default='6 Months', max_length=30),
        ),
        migrations.AddField(
            model_name='courses',
            name='fee',
            field=models.BigIntegerField(default=42000, max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='course_search',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Scopeweb.courses'),
        ),
    ]
