# Generated by Django 5.2.7 on 2025-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0021_courses_duration_courses_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='course_search',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='choose_course',
        ),
        migrations.AddField(
            model_name='registration',
            name='choose_course',
            field=models.ManyToManyField(blank=True, to='Scopeweb.courses'),
        ),
    ]
