# Generated by Django 5.2.7 on 2025-12-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0022_remove_registration_course_search_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='fee',
            field=models.BigIntegerField(default=42000),
        ),
        migrations.AlterField(
            model_name='registration',
            name='photo',
            field=models.FileField(default='media\\documents\\download_7.jpeg', null=True, upload_to='documents'),
        ),
    ]
