# Generated by Django 5.2.7 on 2025-12-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopeweb', '0025_alter_registration_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='photo',
            field=models.FileField(default='documents\\download_7.jpeg', null=True, upload_to='documents'),
        ),
    ]
